(function(global){"use strict";
const KT=global.KohaTools;if(!KT||!KT.Config)return;const ID="circulation-disputes",Scope=KT.getService&&KT.getService("scope");let inserted=null,triggerListener=null,observer=null;
function C(){return KT.Config.getCanonical(ID)}function ready(f){document.readyState==="loading"?document.addEventListener("DOMContentLoaded",f,{once:true}):f()}
function target(c){let t=document.querySelector(c.insertion?.preferredSelector||"")?.closest(c.insertion?.preferredClosest||"li.form-group"),ta=document.querySelector(c.insertion?.textareaSelector||"#borrower_message");if(!t&&ta)for(const s of c.insertion?.textareaClosest||[])if((t=ta.closest(s)))break;if(!t)for(const s of c.insertion?.fallbackSelectors||[])if((t=document.querySelector(s)))break;return {target:t,textarea:ta}}
function inject(c){if(document.getElementById(c.advanced?.duplicateGuardId||"gestion_litiges"))return;const x=target(c);if(!x.target)return;
 const li=document.createElement(c.control?.containerTag||"li");li.className=c.control?.containerClass||"form-group form-row";li.dataset[c.control?.injectedDatasetKey||"kohaInjected"]=String(c.control?.injectedDatasetValue||"gestion-litiges");
 const label=document.createElement("label");label.setAttribute("for",c.control?.selectId||"gestion_litiges");label.className=c.control?.labelClass||"col-form-label";label.textContent=c.control?.label||"Gestion des litiges :";
 const sel=document.createElement("select");sel.id=c.control?.selectId||"gestion_litiges";sel.name=c.control?.selectName||"gestion_litiges";sel.className=c.control?.selectClass||"form-select";
 for(const o of c.options||[]){const op=document.createElement("option");op.value=o.value??"";op.textContent=o.text??o.value??"";sel.appendChild(op)}li.append(label,sel);x.target.insertAdjacentElement(c.insertion?.placement||"afterend",li);inserted=li;
 if(x.textarea){sel.addEventListener("change",()=>{const v=sel.value;if(!v&&c.textarea?.ignoreEmptySelection!==false)return;x.textarea.value=x.textarea.value?x.textarea.value+(c.textarea?.appendSeparator??"\n")+v:v});sel.dataset[c.control?.boundDatasetKey||"bound"]=String(c.control?.boundDatasetValue??"1")}
}
function bind(c){const attach=b=>{if(triggerListener)b.removeEventListener("click",triggerListener);triggerListener=()=>requestAnimationFrame(()=>inject(c));b.addEventListener("click",triggerListener)};
 const b=document.querySelector(c.trigger?.buttonSelector||"#toolbar_addnewmessageLabel");if(b)return attach(b);if(c.trigger?.waitForButton!==false){observer=new MutationObserver((_,o)=>{const x=document.querySelector(c.trigger?.buttonSelector||"");if(x){attach(x);o.disconnect()}});observer.observe(document.documentElement,{childList:true,subtree:true})}}
function run(){const c=C();if(!c?.enabled||!["shadow","live"].includes(c.mode))return;if(Scope&&!Scope.match(c.general?.scope).ok)return;if(c.mode==="shadow"){KT.record({module:ID,level:"info",kind:"shadow-configurable-parity",button:!!document.querySelector(c.trigger?.buttonSelector),options:(c.options||[]).length});return}bind(c)}
function init(){ready(run)}function destroy(){observer?.disconnect();observer=null;const c=C(),b=document.querySelector(c?.trigger?.buttonSelector||"");if(b&&triggerListener)b.removeEventListener("click",triggerListener);triggerListener=null;inserted?.remove();inserted=null}function onConfigChange(){destroy();run()}const runtime={id:ID,init,destroy,onConfigChange};KT.initModule?KT.initModule(runtime):init();
})(window);