(function(global){"use strict";
const KT=global.KohaTools;if(!KT||!KT.Config)return;const ID="shuttle-next-passage",Scope=KT.getService&&KT.getService("scope");let observer=null,addedHeader=null,addedCells=[];
function C(){return KT.Config.getCanonical(ID)}function ready(f){document.readyState==="loading"?document.addEventListener("DOMContentLoaded",f,{once:true}):f()}
function wait(sel,t){return new Promise((res,rej)=>{const n=document.querySelector(sel);if(n)return res(n);const o=new MutationObserver(()=>{const x=document.querySelector(sel);if(x){o.disconnect();clearTimeout(tm);res(x)}});o.observe(document.documentElement,{childList:true,subtree:true});const tm=t>0?setTimeout(()=>{o.disconnect();rej(new Error("timeout"))},t):null})}
function isoWeek(date){const d=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate()));d.setUTCDate(d.getUTCDate()+4-(d.getUTCDay()||7));const y=new Date(Date.UTC(d.getUTCFullYear(),0,1));return Math.ceil((((d-y)/86400000)+1)/7)}
function weekday(name,c){return Number(c.calendar?.weekdayMap?.[String(name||"").toLowerCase()]??0)}function schedule(c){return global.NAVETTE_SCHEDULE||c.schedule?.days||{}}
function next(site,c){if(!site)return null;site=site.trim().toUpperCase();const now=new Date();if((c.calendar?.skipIsoWeeks||[]).includes(isoWeek(now)))return null;let day=null,period=null;const sch=schedule(c);outer:for(const d of Object.keys(sch))for(const p of Object.keys(sch[d]))if((sch[d][p]||[]).map(x=>String(x).toUpperCase()).includes(site)){day=d;period=p;break outer}if(!day)return null;
 const wd=weekday(day,c),cand=new Date(now);if(cand.getDay()!==wd){let add=(wd-cand.getDay()+7)%7;if(add===0)add=7;cand.setDate(cand.getDate()+add)}else{const h=cand.getHours();if(period===c.calendar?.morningLabel&&h>=Number(c.calendar?.morningCutoffHour??12))cand.setDate(cand.getDate()+7);else if(period===c.calendar?.afternoonLabel&&h>=Number(c.calendar?.afternoonCutoffHour??18))cand.setDate(cand.getDate()+7)}
 if((c.calendar?.skipCandidateWeekdays||[]).includes(cand.getDay()))cand.setDate(cand.getDate()+Number(c.calendar?.skipCandidateDays??1));return {date:cand,day,period}}
function daydiff(date){const n=new Date(),a=Date.UTC(date.getFullYear(),date.getMonth(),date.getDate()),b=Date.UTC(n.getFullYear(),n.getMonth(),n.getDate());return Math.ceil((a-b)/86400000)}
function cols(c){const hr=document.querySelector(c.table?.headerRowSelector||"#holds-table thead tr"),labels=hr?[...hr.querySelectorAll("th")].map(h=>String(h.textContent||"").trim().toLowerCase()):[];const get=s=>{for(let i=0;i<labels.length;i++)for(const a of s.aliases||[])if(labels[i].includes(a))return i;return Number(s.fallbackIndex)};return {borrowed:get(c.columns.borrowed),site:get(c.columns.site),status:get(c.columns.status)}}
function addHeader(c,table){const row=table.querySelector("thead tr");if(!row||row.querySelector("th."+c.output.headerClass))return;const th=document.createElement("th");th.classList.add(c.output.headerClass);th.textContent=c.output.headerText;Object.assign(th.style,c.output.headerStyle||{});row.appendChild(th);addedHeader=th}
function process(c){const table=document.querySelector(c.table?.selector||"#holds-table");if(!table)return;addHeader(c,table);const x=cols(c);for(const row of table.querySelectorAll("tbody tr")){const k=c.output?.rowMarkerDatasetKey||"navetteAdded";if(row.dataset[k]===String(c.output?.rowMarkerValue??"true"))continue;const st=row.cells[x.status],site=row.cells[x.site];if(!st||!site){row.dataset[k]=String(c.output.rowMarkerValue);continue}const tx=String(st.textContent||"").trim().toLowerCase();if((c.filter?.skipEmptyStatus!==false&&!tx)||(c.filter?.skipStatusIncludes||[]).some(s=>tx.includes(String(s).toLowerCase()))){row.dataset[k]=String(c.output.rowMarkerValue);continue}
 const td=document.createElement("td");Object.assign(td.style,c.output?.cellStyle||{});const info=next(String(site.textContent||"").trim(),c);if(!info)td.innerHTML=c.output?.unavailableHtml||"Date d'arrivée estimée : <br/>N/A";else{const n=daydiff(info.date),peri=info.period?` (${info.period})`:"",days=Number.isFinite(n)?String(c.output?.daysTemplate||"dans {days} jours").replace(/\{days\}/g,String(n)):"";td.innerHTML=String(c.output?.prefixHtml||"")+info.date.toLocaleDateString(c.output?.locale||"fr-FR")+peri+" <br/>"+days;td.title=String(c.output?.titleTemplate||"").replace(/\{day\}/g,info.day).replace(/\{period\}/g,peri).replace(/\{dateTime\}/g,info.date.toLocaleString(c.output?.locale||"fr-FR"))}row.appendChild(td);addedCells.push(td);row.dataset[k]=String(c.output.rowMarkerValue)}}
function observe(c){const tb=document.querySelector(c.table?.tbodySelector||"#holds-table tbody");if(!tb)return;process(c);observer?.disconnect();observer=new MutationObserver(()=>process(c));observer.observe(tb,{childList:c.observers?.childList!==false,subtree:c.observers?.subtree!==false})}
function run(){const c=C();if(!c?.enabled||!["shadow","live"].includes(c.mode))return;if(Scope&&!Scope.match(c.general?.scope).ok)return;const preview=()=>{const table=document.querySelector(c.table?.selector||"#holds-table");return {table:!!table,rows:table?.querySelectorAll("tbody tr").length||0}};if(c.mode==="shadow"){KT.record({module:ID,level:"info",kind:"shadow-configurable-parity",...preview()});return}
 const tab=document.getElementById(c.table?.tabId||"holds-tab"),start=()=>wait(c.table?.waitRowSelector||"#holds-table tbody tr",Number(c.table?.waitTimeoutMs??2000)).then(()=>observe(c)).catch(()=>requestAnimationFrame(()=>observe(c)));tab?tab.addEventListener("click",start,{once:true}):start()}
function init(){ready(run)}function destroy(){observer?.disconnect();observer=null;addedHeader?.remove();addedHeader=null;for(const td of addedCells){const r=td.closest("tr");td.remove();if(r)delete r.dataset[C().output?.rowMarkerDatasetKey||"navetteAdded"]}addedCells=[]}function onConfigChange(){destroy();run()}const runtime={id:ID,init,destroy,onConfigChange};KT.initModule?KT.initModule(runtime):init();
})(window);