(function(global){"use strict";
const KT=global.KohaTools;if(!KT)return;let observer=null;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function user(){const e=document.querySelector(".loggedinusername[data-loggedinusername]");return String(e?.dataset?.loggedinusername||e?.textContent||"").trim().toLowerCase()}
function visible(node,inherit){if(node?.type==="module"){const c=cfg(node.module),a=KT.getService("access-control");if(c?.enabled===false||c?.mode==="off"||a?.moduleAllowed?.(node.module)===false)return false}const a=node?.audience??inherit;if(!a||a==="all")return true;if(Array.isArray(a))return a.map(x=>String(x).toLowerCase()).includes(user());if(a?.mode==="users")return (a.usernames||[]).map(x=>String(x).toLowerCase()).includes(user());return true}
function href(item){const host=KT.getService("module-host");if(item.type==="module")return host?.url?.(item.module)||"#";if(item.type==="page")return host?.pageUrl?.(item.pageId)||`/cgi-bin/koha/tools/page.pl?page_id=${item.pageId}`;if(item.type==="koha"||item.type==="external")return item.url||"#";return "#"}
function icon(item){return item.icon?`<i class="${esc(item.icon)}" aria-hidden="true"></i> `:""}
function bindAction(a,item){if(item.type==="module")a.addEventListener("click",e=>{e.preventDefault();KT.getService("module-host")?.open?.(item.module)});if(item.type==="action"&&item.action==="dashboard")a.addEventListener("click",e=>{e.preventDefault();global.KohaToolsDashboard?.open?.()})}
function itemLi(item,depth=0,inherit="all"){
 if(!visible(item,inherit))return null;if(item.type==="separator"){const li=document.createElement("li");li.innerHTML='<hr class="dropdown-divider">';return li}
 const li=document.createElement("li"),children=Array.isArray(item.children)?item.children:[];
 if(item.type==="submenu"||children.length){li.className="kt-nested-dropdown";const a=document.createElement("a");a.href="#";a.className="dropdown-item kt-submenu-toggle";a.innerHTML=`${icon(item)}${esc(item.label||"Sous-menu")}<span aria-hidden="true">›</span>`;a.onclick=e=>{e.preventDefault();e.stopPropagation();li.classList.toggle("open")};li.appendChild(a);const ul=document.createElement("ul");ul.className="dropdown-menu kt-submenu";for(const ch of children){const n=itemLi(ch,depth+1,item.audience??inherit);if(n)ul.appendChild(n)}li.appendChild(ul);return li}
 const a=document.createElement("a");a.className="dropdown-item";a.href=href(item);if(item.newTab){a.target="_blank";a.rel="noopener"}a.innerHTML=`${icon(item)}${esc(item.label||item.module||item.url||"Lien")}`;bindAction(a,item);li.appendChild(a);return li
}
function cfg(id){return KT.Config?.getCanonicalPersistent?.(id,true)||{}}
function removeLegacy(){document.querySelectorAll("#michael-tools-menu,.custom-intranet-nav-item").forEach(x=>x.remove())}
function findUserDropdown(){const e=document.querySelector(".loggedinusername[data-loggedinusername]");const dd=e?.closest(".dropdown")?.querySelector(".dropdown-menu");return dd||document.querySelector("#user-menu .dropdown-menu,#logged-in-menu,.user-menu .dropdown-menu,.navbar .dropdown-menu-end")}
function renderUserMenu(){const c=cfg("user-menu-manager"),menu=c.menu||{};document.getElementById("kt-user-tools-section")?.remove();const dd=findUserDropdown();if(!dd||c.enabled===false)return;const li=document.createElement("li");li.id="kt-user-tools-section";li.innerHTML='<hr class="dropdown-divider">';dd.appendChild(li);const root={type:"submenu",label:menu.rootLabel||"Mes outils",icon:menu.icon||"fa fa-wrench",children:menu.items||[],audience:menu.audience||"all"},node=itemLi(root,0,root.audience);if(node){node.id="kt-user-tools-root";dd.appendChild(node)}}
function topLi(item,inherit="all"){
 if(!visible(item,inherit))return null;if(item.type==="separator")return null;const li=document.createElement("li");li.className="nav-item kt-intranet-menu-item";const ch=Array.isArray(item.children)?item.children:[];
 if(item.type==="submenu"||ch.length){li.classList.add("dropdown");const a=document.createElement("a");a.className="nav-link dropdown-toggle";a.href="#";a.setAttribute("data-bs-toggle","dropdown");a.innerHTML=`${icon(item)}<span class="nav-label">${esc(item.label||"Menu")}</span>`;li.appendChild(a);const ul=document.createElement("ul");ul.className="dropdown-menu";for(const x of ch){const n=itemLi(x,1,item.audience??inherit);if(n)ul.appendChild(n)}li.appendChild(ul);return li}
 const a=document.createElement("a");a.className="nav-link";a.href=href(item);if(item.newTab){a.target="_blank";a.rel="noopener"}a.innerHTML=`${icon(item)}<span class="nav-label">${esc(item.label||item.module||"Lien")}</span>`;bindAction(a,item);li.appendChild(a);return li
}
function renderIntranet(){const c=cfg("intranet-nav-manager"),menu=c.menu||{};document.querySelectorAll(".kt-intranet-menu-item").forEach(x=>x.remove());removeLegacy();if(c.enabled===false)return;const ul=document.querySelector("#toplevelmenu");if(!ul)return;for(const item of menu.items||[]){const li=topLi(item,menu.audience||"all");if(li)ul.appendChild(li)}}
function css(){if(document.getElementById("kt-navigation-style"))return;const s=document.createElement("style");s.id="kt-navigation-style";s.textContent=`.kt-nested-dropdown{position:relative}.kt-submenu{display:none;position:absolute;top:-.35rem;right:100%;margin-right:.1rem}.kt-nested-dropdown.open>.kt-submenu{display:block}.kt-submenu-toggle{display:flex!important;align-items:center;justify-content:space-between;gap:1rem}#kt-user-tools-root>.kt-submenu{min-width:250px}.kt-intranet-menu-item .nav-link{display:flex;align-items:center;gap:.25rem}@media(max-width:991.98px){.kt-intranet-menu-item .nav-label{display:none}}`;document.head.appendChild(s)}
function refresh(){css();removeLegacy();renderIntranet();renderUserMenu()}
function watch(){observer?.disconnect();let queued=false;observer=new MutationObserver(()=>{if(queued)return;queued=true;queueMicrotask(()=>{queued=false;if(document.getElementById("michael-tools-menu")||document.querySelector(".custom-intranet-nav-item"))refresh()})});observer.observe(document.documentElement,{childList:true,subtree:true})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>{refresh();watch()},{once:true});else{refresh();watch()}
KT.registerService("navigation",{refresh,href,renderUserMenu,renderIntranet});
})(window);
