(function(global){"use strict";const KT=global.KohaTools;if(!KT)return;
function canonical(id){return KT.Config?.getCanonicalPersistent?.(id,true)||KT.Config?.effective?.canonicalModules?.[id]||{};}function read(obj,path){return String(path||"").split(".").filter(Boolean).reduce((v,k)=>v&&typeof v==="object"?v[k]:undefined,obj)}
function nonEmpty(v){if(v===true)return true;if(typeof v==="number")return Number.isFinite(v)&&v>0;if(typeof v==="string")return v.trim()!==""&&v!=="0";if(Array.isArray(v))return v.length>0;if(v&&typeof v==="object")return Object.keys(v).length>0;return false}
function one(moduleId,p){const c=canonical(moduleId),v=read(c,p.configPath);let resolved=false;if(p.statusProbe==="firebase-config")resolved=!!(c.firebase?.enabled&&c.firebase?.projectId&&c.firebase?.apiKey);else if(p.statusProbe==="manual")resolved=p.configPath?nonEmpty(v):!p.required;else resolved=nonEmpty(v);return {...p,value:v,resolved,blocking:!!p.required&&!resolved};}
function status(moduleId){const list=(canonical(moduleId).prerequisites||[]).map(p=>one(moduleId,p));const blocking=list.filter(x=>x.blocking);return {moduleId,list,blocking,required:list.filter(x=>x.required),ok:!blocking.length,label:!list.length?'Prêt':blocking.length?`${blocking.length} action(s) requise(s)`:'Prêt'};}
function canActivate(moduleId){return status(moduleId).ok;}function sourcePath(p){return p?.copySource||p?.rulesSource||p?.indexSource||p?.workerSource||""}async function source(p){const path=sourcePath(p);if(!path)return"";const root=String(global.KohaToolsBootstrap?.assetRoot||"").replace(/\/?$/,"/");const r=await fetch(root+path,{credentials:"same-origin",cache:"no-store"});if(!r.ok)throw new Error(`prerequisite-source-${r.status}`);return r.text()}
async function copy(p){const text=await source(p);const clip=KT.getService("clipboard");if(clip?.copy)await clip.copy(text);else if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(text);return text;}
async function test(moduleId,pid){const p=status(moduleId).list.find(x=>x.id===pid);if(!p)return {ok:false,reason:'prerequisite-not-found'};if(!p.resolved)return {ok:false,reason:'not-configured',label:'Valeur non renseignée'};if(p.type==='koha-sql-report'){try{const params=p.parameter?[0]:[];const out=await KT.getService('koha-adapter')?.report?.(Number(p.value),params);return {ok:true,label:'Rapport Koha accessible',detail:Array.isArray(out)?`${out.length} ligne(s) retournée(s) lors du test`:''}}catch(e){return {ok:false,reason:'koha-report-failed',label:'Rapport inaccessible',detail:String(e?.message||e)}}}if(p.type==='firebase'||p.type==='firebase-auth')return {ok:true,label:'Configuration présente',detail:'Le contrôle des règles et des droits s’effectue à l’ouverture du module.'};if(p.type==='koha-plugin'||p.type==='privacy-approval'||p.statusProbe==='manual')return {ok:true,label:'Confirmation enregistrée',detail:'Ce prérequis nécessite une validation humaine.'};return {ok:true,label:'Valeur configurée'};}
function all(){const out=[];for(const id of Object.keys(KT.Config?.effective?.canonicalModules||KT.Config?.defaults?.canonicalModules||{}))out.push(status(id));return out;}
KT.registerService("prerequisites",{status,canActivate,all,sourcePath,source,copy,test});})(window);
