(function(global){"use strict";
const KT=global.KohaTools;if(!KT)return;
function clone(v){return v==null?v:JSON.parse(JSON.stringify(v))}function cfg(){return KT.Config?.defaults?.remoteConfig||{}}
function lsGet(k){try{return localStorage.getItem(k)}catch(_){return null}}function lsSet(k,v){try{localStorage.setItem(k,v);return true}catch(_){return false}}
function cacheRead(c,{allowStale=true}={}){if(!c?.cache?.enabled)return null;try{const raw=lsGet(c.cache.storageKey),at=Number(lsGet(c.cache.timestampKey)||0);if(!raw||!at)return null;if(!allowStale&&c.cache.maxAgeMs>0&&Date.now()-at>c.cache.maxAgeMs)return null;return {value:JSON.parse(raw),at}}catch(_){return null}}
function cacheWrite(c,value,{revision=null,fullSync=false}={}){if(!c?.cache?.enabled||!value)return false;try{lsSet(c.cache.storageKey,JSON.stringify(value));lsSet(c.cache.timestampKey,String(Date.now()));if(revision!=null)lsSet(c.cache.revisionStorageKey||"KohaTools.remoteConfig.revision",String(revision));if(fullSync)lsSet(c.cache.fullSyncStorageKey||"KohaTools.remoteConfig.lastFullSyncAt",String(Date.now()));return true}catch(_){return false}}
function cacheTouch(c){try{lsSet(c.cache.timestampKey,String(Date.now()));return true}catch(_){return false}}
function publicWriteEnabled(c){
  if(c?.write?.enabled!==true||String(c?.write?.authMode||"")!=="firebase-auth")return false;
  return KT.getService("firestore-auth")?.isAuthenticated?.()===true;
}function stripRuntimeControl(moduleCfg){const clean=clone(moduleCfg||{});delete clean.mode;if(clean.advanced&&typeof clean.advanced==="object")delete clean.advanced.canary;return clean}
const state={source:"not-loaded",lastReadAt:null,lastFullReadAt:null,lastWriteAt:null,lastError:null,lastWriteMode:null,lastCount:0,revision:null};
async function client(){const svc=KT.getService("firestore");if(!svc)throw new Error("firestore-service-missing");return svc.load()}function paths(){return KT.getService("firestore")?.status?.()||{}}function budget(op,n=1){KT.getService("firebase-budget")?.record?.(cfg().firebaseAppConfig?.projectId,op,n,{kind:"firestore"})}
async function readRevision(db,fsMod){try{const ref=fsMod.doc(db,paths().metaCollectionPath,"config-revision"),snap=await fsMod.getDoc(ref);budget("reads",1);return snap.exists()?String(snap.data()?.revision||snap.data()?.updatedAt||""):null}catch(_){return null}}
async function fullRead(db,fsMod,revision){const snap=await fsMod.getDocs(fsMod.collection(db,paths().configCollectionPath));budget("reads",snap.size);const remote={canonicalModules:{}};snap.forEach(ds=>{const x=ds.data()||{};if(x.payload&&typeof x.payload==="object")remote.canonicalModules[ds.id]=x.payload});cacheWrite(cfg(),remote,{revision,fullSync:true});KT.Config.setRemote(remote);state.lastFullReadAt=new Date().toISOString();state.lastCount=snap.size;return {remote,count:snap.size}}
function applyCache(cached,source){KT.Config.setRemote(cached.value);state.source=source;state.lastReadAt=new Date().toISOString();state.lastError=null;return {source,value:cached.value,count:Object.keys(cached.value?.canonicalModules||{}).length}}
const Remote={
 async bootstrap(options={}){const c=cfg();if(!c.enabled){state.source="disabled";return {source:"disabled",value:null}}const force=options.force===true,cached=cacheRead(c,{allowStale:true}),age=cached?Date.now()-cached.at:Infinity,revalidate=Math.max(60000,Number(c.cache?.revalidateAfterMs)||900000);if(cached&&!force&&age<revalidate)return applyCache(cached,"cache-fresh");
   let error=null;try{const {db,fsMod}=await client(),revKey=c.cache?.revisionStorageKey||"KohaTools.remoteConfig.revision",cachedRev=lsGet(revKey),lastFull=Number(lsGet(c.cache?.fullSyncStorageKey||"KohaTools.remoteConfig.lastFullSyncAt")||0),noRevFull=Math.max(revalidate,Number(c.cache?.fullRefreshWithoutRevisionMs)||21600000);let remoteRev=await readRevision(db,fsMod);
     if(cached&&!force&&remoteRev&&cachedRev===remoteRev){cacheTouch(c);state.revision=remoteRev;return applyCache({...cached,at:Date.now()},"cache-revision-ok")}
     if(cached&&!force&&!remoteRev&&lastFull&&Date.now()-lastFull<noRevFull){cacheTouch(c);return applyCache({...cached,at:Date.now()},"cache-no-revision-window")}
     const {remote,count}=await fullRead(db,fsMod,remoteRev);state.lastReadAt=new Date().toISOString();state.lastError=null;state.revision=remoteRev;state.source=count?"firestore":"firestore-empty";KT.record({module:"remote-config",level:"info",kind:"remote-config-loaded",source:"cloud-firestore",count});return {source:state.source,value:remote,count};
   }catch(e){error=String(e?.message||e);state.lastError=error}
   if(c.failurePolicy==="cache-then-defaults"&&cached){KT.Config.setRemote(cached.value);state.source="cache-stale";KT.record({module:"remote-config",level:"warn",kind:"remote-config-cache-fallback",error});return {source:"cache-stale",value:cached.value,error}}
   state.source="defaults";KT.record({module:"remote-config",level:"warn",kind:"remote-config-defaults-fallback",error});return {source:"defaults",value:null,error}},
 canWrite(){return publicWriteEnabled(cfg())},writeMode(){return this.canWrite()?"firebase-auth":"disabled"},
 async testConnection(){let read=false,write=false,error=null;try{const {db,fsMod}=await client(),meta=KT.getService("firestore")?.metaCollectionPath?.();if(!meta)throw new Error("firestore-meta-path-missing");const ref=fsMod.doc(db,meta,"connection");await fsMod.getDoc(ref);budget("reads",1);read=true;if(this.canWrite()){await fsMod.setDoc(ref,{lastWriteTest:new Date().toISOString(),suiteVersion:KT.version,projectId:cfg().firebaseAppConfig?.projectId||null},{merge:true});budget("writes",1);write=true;state.lastWriteAt=new Date().toISOString();state.lastWriteMode=this.writeMode()}}catch(e){error=String(e?.message||e)}state.lastError=error;return {ok:read&&(!this.canWrite()||write),read,write,mode:this.writeMode(),error,firestore:paths()}},
 async saveCanonical(moduleId,moduleCfg){if(!this.canWrite())return {ok:false,error:"remote-write-disabled"};const clean=stripRuntimeControl(moduleCfg);try{const {db,fsMod}=await client(),revision=`${Date.now()}-${Math.random().toString(36).slice(2,8)}`,batch=fsMod.writeBatch(db),base=paths().configCollectionPath,meta=paths().metaCollectionPath;batch.set(fsMod.doc(db,base,moduleId),{payload:clean,updatedAt:new Date().toISOString(),suiteVersion:KT.version},{merge:false});batch.set(fsMod.doc(db,meta,"config-revision"),{revision,updatedAt:new Date().toISOString(),suiteVersion:KT.version},{merge:true});await batch.commit();budget("writes",2);const cached=cacheRead(cfg(),{allowStale:true})?.value||{canonicalModules:{}};cached.canonicalModules=cached.canonicalModules||{};cached.canonicalModules[moduleId]=clean;cacheWrite(cfg(),cached,{revision});KT.Config.setRemote(cached);state.lastWriteAt=new Date().toISOString();state.lastWriteMode=this.writeMode();state.revision=revision;state.lastError=null;return {ok:true,moduleId,value:clean,mode:this.writeMode()}}catch(e){const error=String(e?.message||e);state.lastError=error;return {ok:false,error}}},
 async publishLocalOverrides(){const local=KT.getLocalOverrides?.()||{},mods=local.canonicalModules||{},ids=Object.keys(mods);if(!ids.length)return {ok:true,count:0};if(!this.canWrite())return {ok:false,error:"remote-write-disabled"};try{const {db,fsMod}=await client(),batch=fsMod.writeBatch(db),base=paths().configCollectionPath,revision=`${Date.now()}-${Math.random().toString(36).slice(2,8)}`;const cached=cacheRead(cfg(),{allowStale:true})?.value||{canonicalModules:{}};for(const id of ids){const payload=stripRuntimeControl(KT.Config.getCanonicalPersistent?.(id,true)||mods[id]);batch.set(fsMod.doc(db,base,id),{payload,updatedAt:new Date().toISOString(),suiteVersion:KT.version});cached.canonicalModules[id]=payload}batch.set(fsMod.doc(db,paths().metaCollectionPath,"config-revision"),{revision,updatedAt:new Date().toISOString(),suiteVersion:KT.version},{merge:true});await batch.commit();budget("writes",ids.length+1);cacheWrite(cfg(),cached,{revision});KT.Config.setRemote(cached);state.lastWriteAt=new Date().toISOString();state.lastWriteMode=this.writeMode();state.revision=revision;state.lastError=null;return {ok:true,count:ids.length,ids}}catch(e){const error=String(e?.message||e);state.lastError=error;return {ok:false,error}}},
 async reload(){return this.bootstrap({force:true})},status(){return {...state,enabled:cfg().enabled===true,provider:"cloud-firestore",firebaseAppConfig:clone(cfg().firebaseAppConfig||{}),firestore:paths(),canWrite:this.canWrite(),writeMode:this.writeMode()}},readCache(){return cacheRead(cfg(),{allowStale:true})?.value||null},clearCache(){const c=cfg();try{for(const k of [c.cache?.storageKey,c.cache?.timestampKey,c.cache?.revisionStorageKey,c.cache?.fullSyncStorageKey])if(k)localStorage.removeItem(k);return true}catch(_){return false}}
};KT.registerService("remote-config",Remote);
})(window);