(function(global){"use strict";
const KT=global.KohaTools;if(!KT)return;
const TTL=24*60*60*1000, promises=new Map();
function clean(v){return String(v||"x").replace(/[^A-Za-z0-9_.-]+/g,"_").slice(0,100)||"x"}
function connection(moduleId,provided){const svc=KT.getService?.("firebase-module");return svc?.get?.(moduleId,provided)||null}
function key(moduleId,c){return `${clean(moduleId)}__${clean(c?.projectId)}__${clean(c?.databaseId||"default")}__${clean(c?.collection||"treeData")}`}
function keys(moduleId,c){const k=key(moduleId,c);return {data:`KohaTools.taxonomy.treeData.v2.${k}`,at:`KohaTools.taxonomy.treeDataAt.v2.${k}`}}
function cached(moduleId,c){const ks=keys(moduleId,c);try{const at=Number(localStorage.getItem(ks.at)||0);if(!at||Date.now()-at>TTL)return null;const rows=JSON.parse(localStorage.getItem(ks.data)||"null");return Array.isArray(rows)?rows:null}catch(_){return null}}
function save(moduleId,c,rows){const ks=keys(moduleId,c);try{localStorage.setItem(ks.data,JSON.stringify(rows||[]));localStorage.setItem(ks.at,String(Date.now()))}catch(_){}return rows||[]}
function clear(moduleId,provided){const c=connection(moduleId,provided);if(!c)return false;const ks=keys(moduleId,c);try{localStorage.removeItem(ks.data);localStorage.removeItem(ks.at);promises.delete(key(moduleId,c));return true}catch(_){return false}}
async function cloud(moduleId,provided){const c=connection(moduleId,provided);if(!c)throw new Error(KT.getService?.("firebase-module")?.problem?.(moduleId,provided)||`Connexion Firebase ${moduleId} non configurée`);const base=`https://www.gstatic.com/firebasejs/${c.sdkVersion||"11.5.0"}`,[a,f,authMod]=await Promise.all([import(base+"/firebase-app.js"),import(base+"/firebase-firestore.js"),c.anonymousAuth?import(base+"/firebase-auth.js"):Promise.resolve(null)]);const conf=KT.getService?.("firebase-module")?.publicConfig?.(moduleId,c,{throwOnError:true});const appName=String(c.appName||`KohaToolsTaxonomy_${clean(moduleId)}`);let app=(a.getApps?.()||[]).find(x=>x.name===appName);if(!app)app=a.initializeApp(conf,appName);if(authMod){const auth=authMod.getAuth(app);if(!auth.currentUser)await authMod.signInAnonymously(auth)}const db=c.databaseId&&c.databaseId!=="(default)"?f.getFirestore(app,c.databaseId):f.getFirestore(app),snap=await f.getDocs(f.collection(db,c.collection||"treeData")),rows=snap.docs.map(d=>({id:d.id,...d.data()}));KT.getService?.("firebase-budget")?.record?.(c.projectId,"reads",snap.size,{kind:"firestore",moduleId});save(moduleId,c,rows);return rows}
async function getRows(moduleId,{force=false,firebase=null}={}){moduleId=String(moduleId||"").trim();if(!moduleId)throw new Error("moduleId requis pour le service taxonomy");const c=connection(moduleId,firebase);if(!c)throw new Error(KT.getService?.("firebase-module")?.problem?.(moduleId,firebase)||`Connexion Firebase ${moduleId} non configurée`);if(!force){const rows=cached(moduleId,c);if(rows)return rows}const k=key(moduleId,c);if(promises.has(k))return promises.get(k);const p=cloud(moduleId,c).finally(()=>promises.delete(k));promises.set(k,p);return p}
function prime(moduleId,rows,{firebase=null}={}){const c=connection(moduleId,firebase);if(!c)return rows||[];return save(moduleId,c,rows||[])}
function status(moduleId){const c=connection(moduleId);return {moduleId,projectId:c?.projectId||null,configured:!!c,problem:KT.getService?.("firebase-module")?.problem?.(moduleId)||null,cached:!!(c&&cached(moduleId,c)),ttlMs:TTL}}
KT.registerService("taxonomy",{getRows,prime,clear,invalidate:clear,status});
})(window);
