(function(global){"use strict";
const KT=global.KohaTools;if(!KT||!KT.Config)return;const ID="history-layout",Scope=KT.getService&&KT.getService("scope");let observer=null,styleNode=null;
function C(){return KT.Config.getCanonical(ID)}function ready(f){document.readyState==="loading"?document.addEventListener("DOMContentLoaded",f,{once:true}):f()}
function d(v){const x=new Date(v);return Number.isNaN(x.getTime())?null:x}function sched(f,c){const p=c.processing?.schedulerPreference||[];if(p.includes("requestIdleCallback")&&typeof requestIdleCallback==="function")requestIdleCallback(f);else requestAnimationFrame(f)}
function style(c){if(c.appearance?.injectDefaultCss===false)return;const id=c.appearance?.styleId||"issuehistory-style";if(document.getElementById(id))return;const s=document.createElement("style");s.id=id;s.textContent=String(c.appearance?.defaultCss||"")+(c.appearance?.customCss?("\n"+c.appearance.customCss):"");document.head.appendChild(s);styleNode=s}
function processRow(row,c){const cells=row.querySelectorAll("td");if(cells.length<Number(c.table?.minimumCells??8))return;const bi=Number(c.columns?.borrowedIndex??5),di=Number(c.columns?.dueIndex??6),ri=Number(c.columns?.returnedIndex??7),cell=cells[ri];if(!cell)return;if(c.advanced?.clearCellClassNameBeforeApply!==false)cell.className="";for(const n of cell.querySelectorAll(c.advanced?.removePreviousMessageSelector||"span.ih-issue-msg"))n.remove();
 const a=c.columns?.dateAttribute||"data-order",b=d(cells[bi]?.getAttribute(a)),due=d(cells[di]?.getAttribute(a)),ret=d(cells[ri]?.getAttribute(a));if(!(b&&due&&ret))return;
 let rule=(c.rules||[]).find(r=>r.condition==="returned-after-due"&&ret>due);if(!rule)rule=(c.rules||[]).find(r=>r.condition==="returned-before-borrowed"&&ret<b);if(!rule)rule=(c.rules||[]).find(r=>r.condition==="otherwise");if(!rule)return;cell.classList.add(rule.className);
 if(rule.message||rule.messageTemplate){const sp=document.createElement("span");sp.className=rule.messageClass||"ih-issue-msg";let tx=rule.message||rule.messageTemplate;if(rule.messageTemplate){const raw=(ret-due)/86400000,n=rule.rounding==="ceil"?Math.ceil(raw):Math.floor(raw);tx=rule.messageTemplate.replace(/\{days\}/g,String(n))}sp.textContent=tx;cell.appendChild(sp)}
}
function highlight(c){const rows=[...document.querySelectorAll(c.table?.rowSelector||"#table_issues tbody tr")];let i=0,chunk=Number(c.processing?.chunkSize??200);function runChunk(){const end=Math.min(i+chunk,rows.length);for(;i<end;i++)try{processRow(rows[i],c)}catch(_){}if(i<rows.length)sched(runChunk,c)}runChunk()}
function attach(c){const tb=document.querySelector(c.table?.tbodySelector||"#table_issues tbody");if(!tb)return false;observer?.disconnect();observer=new MutationObserver(()=>requestAnimationFrame(()=>highlight(c)));observer.observe(tb,{childList:true,subtree:c.processing?.observerSubtree!==false});highlight(c);return true}
function run(){const c=C();if(!c?.enabled||!["shadow","live"].includes(c.mode))return;if(Scope&&!Scope.match(c.general?.scope).ok)return;const rows=document.querySelectorAll(c.table?.rowSelector||"#table_issues tbody tr").length;if(c.mode==="shadow"){KT.record({module:ID,level:"info",kind:"shadow-configurable-parity",rows});return}style(c);if(attach(c))return;const docObs=new MutationObserver((_,o)=>{if(attach(c))o.disconnect()});docObs.observe(document.documentElement||document.body,{childList:true,subtree:true})}
function init(){ready(run)}function destroy(){observer?.disconnect();observer=null;styleNode?.remove();styleNode=null}function onConfigChange(){destroy();run()}const runtime={id:ID,init,destroy,onConfigChange};KT.initModule?KT.initModule(runtime):init();
})(window);