(function(global){"use strict";
const KT=global.KohaTools;if(!KT)return;
const KEY="KohaTools.maintenanceBaseline.v1";
let manifest=null,defaults=null;
function stable(v){if(Array.isArray(v))return '['+v.map(stable).join(',')+']';if(v&&typeof v==='object')return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+stable(v[k])).join(',')+'}';return JSON.stringify(v)}
function hash(v){let h=2166136261,s=stable(v);for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16).padStart(8,'0')}
function ids(){return [...new Set((manifest?.modules||[]).map(m=>defaults?.modules?.[m.id]?.config?.canonicalModule).filter(Boolean))]}
function moduleSnapshot(cid){const cfg=KT.Config?.getCanonicalPersistent?.(cid,true)||{},pr=KT.getService('prerequisites')?.status?.(cid)||{ok:true,blocking:[]},hs=KT.getService('health')?.stateFor?.(cid)||{},v=KT.getService('validation')?.get?.(cid)||{},t=KT.getHealthTelemetry?.(cid)||{};return {canonicalId:cid,enabled:cfg.enabled!==false,mode:cfg.mode||'',configHash:hash(cfg),prerequisitesOk:!!pr.ok,blocking:(pr.blocking||[]).map(x=>x.id),health:hs.state||'unseen',validation:v.state||'untested',kohaVersion:v.kohaVersion||null,lastInitOk:t.lastInitOk!==false,initErrors:Number(t.initErrors||0)};}
function snapshot(kind='manual'){const koha=KT.getService('health')?.kohaVersion?.()||KT.getService('koha-adapter')?.kohaVersion?.()||'';return {schema:'KohaTools.maintenance-baseline.v1',kind,at:new Date().toISOString(),suiteVersion:KT.version,kohaVersion:koha,deploymentMode:KT.deploymentMode,modules:Object.fromEntries(ids().map(id=>[id,moduleSnapshot(id)]))};}
function save(kind='pre-koha-update'){const s=snapshot(kind);localStorage.setItem(KEY,JSON.stringify(s));return s}
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch(_){return null}}
function clear(){localStorage.removeItem(KEY)}
function compare(){const before=read(),now=snapshot('comparison');if(!before)return {ok:false,reason:'no-baseline',now};const changes=[];for(const id of new Set([...Object.keys(before.modules||{}),...Object.keys(now.modules||{})])){const a=before.modules?.[id],b=now.modules?.[id];if(!a||!b){changes.push({canonicalId:id,type:!a?'added':'removed',before:a||null,now:b||null});continue}const reasons=[];if(a.configHash!==b.configHash)reasons.push('configuration');if(a.prerequisitesOk&&!b.prerequisitesOk)reasons.push('prérequis');if(['proven','technical-ok'].includes(a.health)&&!['proven','technical-ok'].includes(b.health))reasons.push('santé');if(b.health==='broken')reasons.push('anomalie');if(b.initErrors>a.initErrors)reasons.push('erreur d’initialisation');if(reasons.length)changes.push({canonicalId:id,type:'changed',reasons,before:a,now:b})}const kohaChanged=String(before.kohaVersion||'')!==String(now.kohaVersion||'');const suiteChanged=String(before.suiteVersion||'')!==String(now.suiteVersion||'');const attention=Object.values(now.modules||{}).filter(x=>x.enabled&&(!x.prerequisitesOk||['broken','recheck-koha'].includes(x.health)||x.initErrors>0));return {ok:true,before,now,kohaChanged,suiteChanged,changes,attention};}
function targetedIds(){const out=new Set();const cmp=compare();for(const id of KT.getService('updates')?.activeImpact?.()||[])out.add(id);if(cmp.ok){for(const x of cmp.changes||[])if(x.canonicalId)out.add(x.canonicalId);for(const x of cmp.attention||[])if(x.canonicalId)out.add(x.canonicalId);if(cmp.kohaChanged){const compat=KT.getService('compatibility');for(const id of ids())if(compat?.affectedAfterKohaUpdate?.(id))out.add(id)}}return [...out].filter(id=>(KT.Config?.getCanonicalPersistent?.(id,true)||{}).enabled!==false)}
function targeted(){return targetedIds().map(canonicalId=>({canonicalId,status:KT.getService('health')?.moduleStatus?.(canonicalId)||{},compatibility:KT.getService('compatibility')?.strategy?.(canonicalId)||{},targets:KT.getService('recipe')?.targetLinks?.(canonicalId)||[]}))}
function runTargetedCurrentPage(){const wanted=new Set(targetedIds()),R=KT.getService('recipe');if(!R)return {ok:false,reason:'recipe-service-missing',results:[]};const rel=(R.relevant?.({includeGlobal:true})||[]).map(x=>x.canonicalId).filter(id=>wanted.has(id));const results=rel.map(id=>R.testOne?.(id)).filter(Boolean);results.forEach(r=>KT.getService('health')?.observeResult?.(r));return {ok:true,count:results.length,canonicalIds:rel,results}}
function diagnostic(cid=null){const perf=KT.getService('performance')?.summary?.()||{},cmp=compare(),all=cid?[moduleSnapshot(cid)]:ids().map(moduleSnapshot);const ds=(KT.diagnostics||[]).filter(d=>!cid||d.canonicalId===cid||d.module===cid).slice(-100).map(d=>({at:d.at,level:d.level,module:d.module,canonicalId:d.canonicalId,kind:d.kind,message:d.message}));return {schema:'KohaTools.public-diagnostic.v1',generatedAt:new Date().toISOString(),suiteVersion:KT.version,kohaVersion:KT.getService('health')?.kohaVersion?.()||'',deploymentMode:KT.deploymentMode,location:{path:location.pathname},modules:all,comparison:cmp.ok?{baselineAt:cmp.before.at,baselineKoha:cmp.before.kohaVersion,kohaChanged:cmp.kohaChanged,suiteChanged:cmp.suiteChanged,changes:cmp.changes.map(x=>({canonicalId:x.canonicalId,type:x.type,reasons:x.reasons||[]}))}:null,performance:{boot:perf.boot,resources:perf.resources,slow:(perf.slow||[]).slice(0,20)},diagnostics:ds};}
function download(cid=null){const data=diagnostic(cid),blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`pimp-my-koha-diagnostic-${cid||'global'}-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),500);return data}
function init(m,d){manifest=m;defaults=d}
KT.registerService('maintenance',{init,snapshot,save,read,clear,compare,targetedIds,targeted,runTargetedCurrentPage,diagnostic,download,moduleSnapshot});
})(window);
