(function(global){"use strict";const KT=global.KohaTools;if(!KT)return;
function canonical(id){return KT.Config?.getCanonicalPersistent?.(id,true)||KT.Config?.effective?.canonicalModules?.[id]||{};}function read(obj,path){return String(path||"").split(".").filter(Boolean).reduce((v,k)=>v&&typeof v==="object"?v[k]:undefined,obj)}
function nonEmpty(v){if(v===true)return true;if(typeof v==="number")return Number.isFinite(v)&&v>0;if(typeof v==="string")return v.trim()!==""&&v!=="0";if(Array.isArray(v))return v.length>0;if(v&&typeof v==="object")return Object.keys(v).length>0;return false}
function versionParts(v){const m=String(v||"").match(/(\d{2})\.(\d{2})(?:\.(\d{1,2}))?/);return m?[Number(m[1]),Number(m[2]),Number(m[3]||0)]:null}
function versionCompare(a,b){const x=versionParts(a),y=versionParts(b);if(!x||!y)return null;for(let i=0;i<3;i++){if(x[i]!==y[i])return x[i]<y[i]?-1:1}return 0}
function currentKohaVersion(){return KT.getService("health")?.kohaVersion?.()||KT.getService("recipe")?.currentKohaVersion?.()||null}
function applies(p){const v=currentKohaVersion();if(!v)return p?.versionUnknownPolicy!=="skip";if(p?.minKohaVersion&&versionCompare(v,p.minKohaVersion)<0)return false;if(p?.maxKohaVersionExclusive&&versionCompare(v,p.maxKohaVersionExclusive)>=0)return false;return true}
function blockingScope(p){const s=String(p?.blockingScope||"module").toLowerCase();return ["capability","feature"].includes(s)?s:"module"}
function one(moduleId,p){const c=canonical(moduleId),v=read(c,p.configPath),applicable=applies(p);let resolved=!applicable;if(applicable){if(p.statusProbe==="firebase-config")resolved=!!(c.firebase?.enabled&&c.firebase?.projectId&&c.firebase?.apiKey);else if(p.statusProbe==="manual")resolved=p.configPath?nonEmpty(v):!p.required;else resolved=nonEmpty(v)}const scope=blockingScope(p),missingRequired=applicable&&!!p.required&&!resolved;return {...p,value:v,applicable,resolved,blockingScope:scope,missingRequired,blocking:missingRequired&&scope==="module"};}
function status(moduleId){const list=(canonical(moduleId).prerequisites||[]).map(p=>one(moduleId,p));const blocking=list.filter(x=>x.blocking),unresolvedRequired=list.filter(x=>x.missingRequired),capabilityBlocking=unresolvedRequired.filter(x=>x.blockingScope!=="module");return {moduleId,list,blocking,unresolvedRequired,capabilityBlocking,required:list.filter(x=>x.required),ok:!blocking.length,label:!list.length?"Prêt":blocking.length?`${blocking.length} action(s) requise(s)`:capabilityBlocking.length?`Prêt · ${capabilityBlocking.length} fonction(s) à configurer`:"Prêt"};}
function statusFor(moduleId,capability){const s=status(moduleId),cap=String(capability||"");if(!cap)return s;const relevant=s.list.filter(x=>x.applicable!==false&&(x.blockingScope==="module"||!Array.isArray(x.capabilities)||x.capabilities.includes(cap)));const blocking=relevant.filter(x=>x.missingRequired);return {...s,capability:cap,relevant,blocking,ok:!blocking.length,label:blocking.length?`${blocking.length} action(s) requise(s)`:"Prêt"};}
function canActivate(moduleId,capability){return (capability?statusFor(moduleId,capability):status(moduleId)).ok;}function sourcePath(p){return p?.copySource||p?.rulesSource||p?.indexSource||p?.workerSource||""}async function source(p){const path=sourcePath(p);if(!path)return"";const root=String(global.KohaToolsBootstrap?.assetRoot||"").replace(/\/?$/,"/");const r=await fetch(root+path,{credentials:"same-origin",cache:"no-store"});if(!r.ok)throw new Error(`prerequisite-source-${r.status}`);return r.text()}
async function copy(p){const text=await source(p);const clip=KT.getService("clipboard");if(clip?.copy)await clip.copy(text);else if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(text);return text;}
async function test(moduleId,pid){const p=status(moduleId).list.find(x=>x.id===pid);if(!p)return {ok:false,reason:"prerequisite-not-found"};if(p.applicable===false)return {ok:true,label:"Non requis pour cette version de Koha"};if(!p.resolved)return {ok:false,reason:"not-configured",label:"Valeur non renseignée"};if(p.type==="koha-sql-report"){try{const params=p.parameter?[0]:[];const out=await KT.getService("koha-adapter")?.report?.(Number(p.value),params);return {ok:true,label:"Rapport Koha accessible",detail:Array.isArray(out)?`${out.length} ligne(s) retournée(s) lors du test`:""}}catch(e){return {ok:false,reason:"koha-report-failed",label:"Rapport inaccessible",detail:String(e?.message||e)}}}if(p.type==="firebase"||p.type==="firebase-auth")return {ok:true,label:"Configuration présente",detail:"Le contrôle des règles et des droits s’effectue à l’ouverture du module."};if(p.type==="koha-plugin"||p.type==="privacy-approval"||p.statusProbe==="manual")return {ok:true,label:"Confirmation enregistrée",detail:"Ce prérequis nécessite une validation humaine."};return {ok:true,label:"Valeur configurée"};}
function all(){const out=[];for(const id of Object.keys(KT.Config?.effective?.canonicalModules||KT.Config?.defaults?.canonicalModules||{}))out.push(status(id));return out;}
KT.registerService("prerequisites",{status,statusFor,canActivate,all,sourcePath,source,copy,test,currentKohaVersion,versionCompare});})(window);
